# -*- mode: ruby; coding: utf-8; -*-

PODSPEC = "Requests.podspec"

default_platform(:ios)

desc "Performs the prerequisite tasks for a patch release"
lane :prep_patch do
  prepare_release("patch")
end

desc "Performs the prerequisite tasks for a minor release"
lane :prep_minor do
  prepare_release("minor")
end

desc "Performs the prerequisite tasks for a major release"
lane :prep_major do
  prepare_release("minor")
end

def prepare_release(bump_type)
  pod_lib_lint
  version = increment_version_number(bump_type: bump_type)
  version_bump_podspec(path: PODSPEC, version_number: version)
  commit_version_bump(include: PODSPEC)
  add_git_tag(tag: "v#{version}")
end
